using CarMaintenance.Data;
using CarMaintenance.Models;
using CarMaintenance.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using System;
using System.IO;
using System.Linq;

namespace CarMaintenance.Controllers
{
    public class ReportsController : Controller
    {
        private readonly AppDbContext _db;

        public ReportsController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View("Search");
        }

        public IActionResult Search(string searchTerm)
        {
            // Load customers with related data
            var customers = _db.Tbl_Customers
                .Include(c => c.Cars)
                .Include(c => c.Receipts)
                    .ThenInclude(r => r.ReceiptsDetails)
                        .ThenInclude(d => d.Services)
                .ToList();

            // Load transfers with related data
            var transfers = _db.Tbl_TransferCars
                .Include(t => t.FromCustomers)
                .Include(t => t.ToCustomers)
                .Include(t => t.Cars)
                .ToList();

            // Filter and prepare results
            var results = customers
                .Where(c => string.IsNullOrEmpty(searchTerm) ||
                            c.Name.Contains(searchTerm) ||
                            c.Email.Contains(searchTerm) ||
                            (c.Cars != null && c.Cars.NumberPlate.Contains(searchTerm)))
                .Select(c => new SearchResultViewModel
                {
                    Customer = c,
                    Transfers = transfers
                        .Where(t => t.FromCustomerID == c.CustomerID || t.ToCustomerID == c.CustomerID)
                        .ToList()
                })
                .ToList();

            // Get logged-in user
            var userId = HttpContext.Session.GetInt32("UserId");
            string userName = "Unknown User";

            if (userId.HasValue)
            {
                var user = _db.Tbl_Users.Find(userId.Value);
                if (user != null)
                {
                    userName = $"{user.FirstName} {user.LastName}";
                }
            }

            ViewData["GeneratedBy"] = userName;
            ViewData["SearchTerm"] = searchTerm;

            return View("SearchResults", results);
        }

        public IActionResult ExportPdf(string searchTerm)
        {
            // Load data same as Search()
            var customers = _db.Tbl_Customers
                .Include(c => c.Cars)
                .Include(c => c.Receipts)
                    .ThenInclude(r => r.ReceiptsDetails)
                        .ThenInclude(d => d.Services)
                .ToList();

            var transfers = _db.Tbl_TransferCars
                .Include(t => t.FromCustomers)
                .Include(t => t.ToCustomers)
                .Include(t => t.Cars)
                .ToList();

            var results = customers
                .Where(c => string.IsNullOrEmpty(searchTerm) ||
                            c.Name.Contains(searchTerm) ||
                            c.Email.Contains(searchTerm) ||
                            (c.Cars != null && c.Cars.NumberPlate.Contains(searchTerm)))
                .Select(c => new SearchResultViewModel
                {
                    Customer = c,
                    Transfers = transfers
                        .Where(t => t.FromCustomerID == c.CustomerID || t.ToCustomerID == c.CustomerID)
                        .ToList()
                })
                .ToList();

            var userId = HttpContext.Session.GetInt32("UserId");
            string userName = "Unknown User";
            if (userId.HasValue)
            {
                var user = _db.Tbl_Users.Find(userId.Value);
                if (user != null)
                {
                    userName = $"{user.FirstName} {user.LastName}";
                }
            }

            using (var ms = new MemoryStream())
            {
                var writer = new PdfWriter(ms);
                var pdf = new PdfDocument(writer);
                var document = new Document(pdf);

                document.Add(new Paragraph("Customer Report").SetFontSize(18).SetBold());
                document.Add(new Paragraph($"Generated By: {userName}").SetFontSize(12));
                document.Add(new Paragraph($"Generated On: {DateTime.Now}").SetFontSize(12));
                document.Add(new Paragraph(" "));

                foreach (var r in results)
                {
                    document.Add(new Paragraph($"Customer: {r.Customer.Name} ({r.Customer.Email})").SetBold());
                    document.Add(new Paragraph($"Number Plate: {r.Customer.Cars?.NumberPlate ?? "N/A"}"));

                    document.Add(new Paragraph("Receipts:"));
                    foreach (var rec in r.Customer.Receipts)
                    {
                        document.Add(new Paragraph($"- Date: {rec.Date.ToShortDateString()}, Amount: {rec.TotalAmount}"));
                        foreach (var d in rec.ReceiptsDetails)
                        {
                            document.Add(new Paragraph($"   • Service: {d.Services?.ServiceName ?? "N/A"}"));
                        }
                    }

                    document.Add(new Paragraph("Transfers:"));
                    foreach (var t in r.Transfers)
                    {
                        document.Add(new Paragraph(
                            $"- {t.FromCustomers?.Name ?? "N/A"} → {t.ToCustomers?.Name ?? "N/A"} on {t.TransferDate.ToShortDateString()}, Number Plate: {t.Cars?.NumberPlate ?? "N/A"}"));
                    }

                    document.Add(new Paragraph(" "));
                }

                document.Close();
                return File(ms.ToArray(), "application/pdf", "CustomerReport.pdf");
            }
        }
    }
}
